Algoritmo "repita"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : nivia
// Descrição   : tabuada
// Autor(a)    : giovana e helena
// Data atual  : 02/04/2023
Var
// Seção de Declarações das variáveis 
num, result:real
i:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
i:=1
 escreva ("Digite o numero:")
 leia (num)
 repita
 result:=num*i
 i:=i+1
  escreval (result)
ate (i>=10)

Fimalgoritmo